# Numpy - the numerical module of Python

### Numpy is the numerical module of Python. It’s a powerful N-dimensional array tool that is efficient for handling large datasets (e.g., images, high resolution spectra etc). In today's class we will learn how to use some of the basic numpy functions. If you want to get more fluent with numpy try the numpy tutorial:  https://numpy.org/devdocs/user/quickstart.html  

### The numerical package of Python. With it you can: 

- Make and manipulate sophisticated (broadcasting) arrays
- Read and work on (N-dimensional) data
- Do linear algebra, Fourier transformations; has random number capabilities

### **Scipy** is the complimentary package. As a rule of thumb, if something is covered in a general textbook on numerical computing, it’s probably implemented in SciPy.


### Let's get started and see it in action:

### The most important thing always is to remember to start by importing numpy:

In [1]:
import numpy as np

### This imports the complete module numpy. The “as np” part is there to make typing more efficient for you: you now need to type only *np.function()* when you want to call a function from numpy, rather than *numpy.function()* . 
### Since later in the demo we will plot somethings as well, import the plotting module:


In [2]:
import matplotlib.pyplot  as plt   
## remember that if you knew --for some very weird case-- that you only need 1 or 2 packages you could just import
## those with: from matplotlib.pyplot import plot or (plot, xlabel, ylabel...)

### Let’s create our first numpy array. An array that starts at 1 and finishes at 100 with a step of 1:


In [3]:
x_numpy = np.arange( 1, 100, 1 ) 

In [4]:
print( type ( x_numpy ) )
print( x_numpy )

<class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


### To see the differences between numpy arrays and lists, and how efficient numpy is in numerical computing, let’s also create a list that is similar:


In [5]:
x_list = list( range(1, 100, 1) )


In [6]:
print( x_list )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


### Now let’s see the difference between the two when we want to multiple our arrays with a constant. 

### For the numpy array do : 

In [7]:
print( x_numpy * 10 )

[ 10  20  30  40  50  60  70  80  90 100 110 120 130 140 150 160 170 180
 190 200 210 220 230 240 250 260 270 280 290 300 310 320 330 340 350 360
 370 380 390 400 410 420 430 440 450 460 470 480 490 500 510 520 530 540
 550 560 570 580 590 600 610 620 630 640 650 660 670 680 690 700 710 720
 730 740 750 760 770 780 790 800 810 820 830 840 850 860 870 880 890 900
 910 920 930 940 950 960 970 980 990]


### If you try the same for the list:  x_list * 10  what do you get?

In [8]:
print( x_list * 10 )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59

### Lists are not arrays. To do numerical computations with their elements we need to call them one by one. 
### You need a for loop or this: [i*10 for i in x_list] and you will get the same results as with x_numpy * 10. 


In [9]:
for i in range( len( x_list ) ):
    print( x_list[i] * 10 )

10
20
30
40
50
60
70
80
90
100
110
120
130
140
150
160
170
180
190
200
210
220
230
240
250
260
270
280
290
300
310
320
330
340
350
360
370
380
390
400
410
420
430
440
450
460
470
480
490
500
510
520
530
540
550
560
570
580
590
600
610
620
630
640
650
660
670
680
690
700
710
720
730
740
750
760
770
780
790
800
810
820
830
840
850
860
870
880
890
900
910
920
930
940
950
960
970
980
990


In [10]:
#or simpler: 
[ i*10 for i in x_list ]   # ---> "list comprehension" see later class

[10,
 20,
 30,
 40,
 50,
 60,
 70,
 80,
 90,
 100,
 110,
 120,
 130,
 140,
 150,
 160,
 170,
 180,
 190,
 200,
 210,
 220,
 230,
 240,
 250,
 260,
 270,
 280,
 290,
 300,
 310,
 320,
 330,
 340,
 350,
 360,
 370,
 380,
 390,
 400,
 410,
 420,
 430,
 440,
 450,
 460,
 470,
 480,
 490,
 500,
 510,
 520,
 530,
 540,
 550,
 560,
 570,
 580,
 590,
 600,
 610,
 620,
 630,
 640,
 650,
 660,
 670,
 680,
 690,
 700,
 710,
 720,
 730,
 740,
 750,
 760,
 770,
 780,
 790,
 800,
 810,
 820,
 830,
 840,
 850,
 860,
 870,
 880,
 890,
 900,
 910,
 920,
 930,
 940,
 950,
 960,
 970,
 980,
 990]

### What happens though, when we have a *large* array we want to work with? Let’s make a new array that goes from 1 to 240,000 with a step of 1:


In [11]:
%%time
x_numpy_new = np.arange(1, 240000, 1)   ### note I keep this one small....try pushing it to 1,000,000 and see the
                                        ### difference even more obv 

CPU times: user 1.06 ms, sys: 1.14 ms, total: 2.21 ms
Wall time: 967 µs


### and a similar new list:


In [12]:
%%time
x_list_new = list( range( 1, 240000, 1) )

CPU times: user 5.02 ms, sys: 2.29 ms, total: 7.31 ms
Wall time: 7.28 ms


### Now let’s calculate the square of a new, even larger array:


In [13]:
x_numpy2 = np.arange( 1, 10000000, 1)
x_list2  = list( x_numpy2 )

In [14]:
%%time

y_numpy2 = x_numpy2 **2 


CPU times: user 18.2 ms, sys: 16.3 ms, total: 34.5 ms
Wall time: 33.3 ms


In [15]:
print( x_numpy2, y_numpy2)

[      1       2       3 ... 9999997 9999998 9999999] [             1              4              9 ... 99999940000009
 99999960000004 99999980000001]


### works nice and fast...let's do the same for the list:

In [16]:
%%time
y_list2 = [i**2 for i in x_list2]


CPU times: user 1.82 s, sys: 106 ms, total: 1.92 s
Wall time: 1.92 s


### As you might have noticed, it takes (much) longer to do this with a list than with numpy! (for 10,000,000 it's a factor of 90 or more for my laptop)


### another example of the power of numpy (and of tricky bugs): 
<img src="../plots/bug_np.png" width=600 height=600 />


In [17]:
# let's test what this person does in the start (since we imported numpy we 'll use np.cos):
wj0 = []
N1 = 5000000

In [18]:
print( wj0)

[]


In [19]:
%%time
for i in range( 0, N1 ):   ## create a range 0 to N1. Then for every element in the range scan it 1 by 1 and assign
                           ## that value to i
    w = 0.5 * ( 1 - np.cos( 2 * np.pi * i / N1 ) )  ## use this value to make a cos function of i 
    wj0.append( w )        ## append it to the end of the list to make your list

CPU times: user 6.12 s, sys: 61.2 ms, total: 6.18 s
Wall time: 6.18 s


In [20]:
## takes some time and gives:
print( wj0[ :100] )

[0.0, 3.9479530755670567e-13, 1.5791257190755914e-12, 3.5530467457078885e-12, 6.316558387453597e-12, 9.869605133161485e-12, 1.4212242493982785e-11, 1.9344414958766265e-11, 2.5266178038663156e-11, 3.197753173367346e-11, 3.947842053264594e-11, 4.7768899946731835e-11, 5.684891446477991e-11, 6.67185195979414e-11, 7.737771534621629e-11, 8.882644619845337e-11, 1.0106476766580386e-10, 1.1409262423711652e-10, 1.279100714235426e-10, 1.425171092250821e-10, 1.5791368213058377e-10, 1.7409984565119885e-10, 1.910755442757761e-10, 2.0884083351546678e-10, 2.2739565785911964e-10, 2.4674012832903713e-10, 2.668740783917656e-10, 2.8779767458075867e-10, 3.0951080587371393e-10, 3.320134722706314e-10, 3.5530578479381347e-10, 3.793875769098065e-10, 4.042590151520642e-10, 4.2991998849828406e-10, 4.563704969484661e-10, 4.836105960137616e-10, 5.116402856941704e-10, 5.404595104785415e-10, 5.700683258780259e-10, 6.004667318926238e-10, 6.316546730111838e-10, 6.636322047448573e-10, 6.963992715824929e-10, 7.299559290

In [21]:
%%time 
# now let's numpy it:
n = np.arange(0, N1, 1)

# instead of looping over i we create an array of all the x-variables :
# and then we make the numpy cos array:

wj02 = 0.5 * ( 1 - np.cos( 2 * np.pi * n / N1 ) )



CPU times: user 84.2 ms, sys: 28.3 ms, total: 112 ms
Wall time: 112 ms


In [22]:
# done in a fraction of the time that the appending to list needed....if for whatever 
# reason you *needed* a list you can always list() it:

print( wj02[ :100 ] )

[0.00000000e+00 3.94795308e-13 1.57912572e-12 3.55304675e-12
 6.31655839e-12 9.86960513e-12 1.42122425e-11 1.93444150e-11
 2.52661780e-11 3.19775317e-11 3.94784205e-11 4.77688999e-11
 5.68489145e-11 6.67185196e-11 7.73777153e-11 8.88264462e-11
 1.01064768e-10 1.14092624e-10 1.27910071e-10 1.42517109e-10
 1.57913682e-10 1.74099846e-10 1.91075544e-10 2.08840834e-10
 2.27395658e-10 2.46740128e-10 2.66874078e-10 2.87797675e-10
 3.09510806e-10 3.32013472e-10 3.55305785e-10 3.79387577e-10
 4.04259015e-10 4.29919988e-10 4.56370497e-10 4.83610596e-10
 5.11640286e-10 5.40459510e-10 5.70068326e-10 6.00466732e-10
 6.31654673e-10 6.63632205e-10 6.96399272e-10 7.29955929e-10
 7.64302177e-10 7.99437960e-10 8.35363334e-10 8.72078243e-10
 9.09582742e-10 9.47876833e-10 9.86960458e-10 1.02683362e-09
 1.06749642e-09 1.10894877e-09 1.15119064e-09 1.19422211e-09
 1.23804317e-09 1.28265376e-09 1.32805394e-09 1.37424372e-09
 1.42122303e-09 1.46899193e-09 1.51755036e-09 1.56689839e-09
 1.61703601e-09 1.667963

In [23]:
#what types are they?

In [24]:
print( type( wj02 ) )
print( type( list(wj02) ) )


<class 'numpy.ndarray'>
<class 'list'>


### Let’s create an array of 10 elements that are all 0:

In [25]:
x = np.zeros( 10 )
print( x )

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### and an array of 10 elements that are all 1:

In [26]:
y = np.ones( 10 )
print( y )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


### Let’s do some math with them:

In [27]:
# add x and y:

print( x + y )
# get the x minus y:

print( x - y )

#add 5 to x :

print( x + 5 )

# multiply x and y:

print( x * y )

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


### How does numpy treat these arrays for the numerical calculations?  

In [28]:
# make array sum_xy whose elements are the sum of the corresponding elements of x times 2 and y times 3

In [29]:
sum_xy = ( x * 2 ) + ( y * 3)

In [30]:
print( sum_xy )

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]


### Let's make a 2D array:


In [31]:

data = np.array( [ [1 , 3  , 5  ], 
                   [7 , 9  , 11 ], 
                   [13, 15 , 17 ]    ]  )

### Let's check how numpy reads the table:

In [32]:
print( data[ 0, 0 ] )

1


In [33]:
print( data[ 0, 1 ] )

3


In [34]:
print( data[ 1, 0 ] )

7


In [35]:
## how can I get all elements of the first line?

print( data[ 0, : ])

[1 3 5]


In [36]:
print( data[ 0, : 2  ])

[1 3]


In [37]:
## how can I get all elements of the first two columns ?

print( data[ 0:2 , 0:2  ])


[[1 3]
 [7 9]]


### Now let’s create a 2x2 array of zeros:

In [38]:
z = np.zeros( ( 2 , 2 ) )  #---> note the extra ( ) to show it's a 2d array
print( z )

[[0. 0.]
 [0. 0.]]


### You can check the shape of your array out with: .shape

In [39]:
print( z.shape )

(2, 2)


In [40]:
#try:
print( z + 5 )

[[5. 5.]
 [5. 5.]]


### and try to multiply it with x.  What happens? Why doesn’t it work?


In [41]:
z * x 

ValueError: operands could not be broadcast together with shapes (2,2) (10,) 

### Let’s now change z to be a 10x2 array of ones: 

In [ ]:
z = np.ones( ( 10 , 2 ) )

### try z \* x and x \* z. 


In [ ]:
z * x

In [ ]:
x * z 

### Why don’t they work? 


In [ ]:
# try:

a1 = np.array( [ [1, 2] , 
                 [3, 4] ] )
b1 = np.ones( ( 2, 2 ) )

print( a1 )
print( b1 )


In [ ]:
print( a1 * b1 )

### how does “ \* ” work?

### “ \* ” does element by element multiplication, not matrix multiplication. The different dimensions of your x and z arrays means that * cannot operate as it should. Python gives an error message to warn you that you try something “illegal”. 

### What we need since we have two matrices with different dimensions is np.matmul(x,z) . This will give us a (1,2) x (2,2) => (1,2) array, as it should!


In [ ]:
x = np.arange(0, 2 )
z = np.ones( ( 2 , 2 ) )


print( x.size, z.size )
print ( np.matmul ( x, z ) )

In [ ]:
print ( np.matmul ( a1, b1 ) )

### A feature of Python is “broadcasting”. When some conditions are met, Python will allow you to multiply arrays that have different dimensions. The smaller array is broadcast across the larger array so that they have compatible shapes. For example, create an array 


In [ ]:
z_2 = np.array( [ 5 ] )

In [ ]:
print( z_2.size, type( z_2 ) )

### and add it to your array z.  Following the strict rules of math this should not work! However, Python allows you to do this using broadcasting:

In [ ]:
print( z_2 + z )

###  What it does is it ‘creates’ a (2,2) array of 5s and adds it to your array z following the element-by-element rules of matrix addition (same for multiplication etc). 


### Let’s create an array q that goes from 0 to 100 with a step of 0.1, and a q_cos that is the cosine of q:


In [ ]:
q     = np.arange( 0, 100, 0.1)
q_cos = np.cos( q )

### and and array q_sin that is the sine of q:


In [ ]:
q_sin = np.sin( q )

### Let’s plot q_cos and q_sin as a function of q :

In [ ]:
plt.figure( figsize = ( 12, 10 )  )
plt.plot( q, q_cos, color= 'red'  ) 
plt.plot( q, q_sin, color= 'blue' )


### This is a lot of information. Let’s only focus on what happens from q[0] to q[100] :


In [ ]:
plt.figure( figsize = ( 5, 5 )  )
plt.plot( q[ 0: 100 ] , q_cos[ 0: 100 ] , color= 'red'  ) 
plt.plot( q[ 0: 100 ], q_sin[ 0: 100 ] , color= 'blue' )


### Better! As you can see we can *slice* a numpy array. 

### Let’s try some more slicing. 


In [ ]:
z = np.arange( 1,20 )

In [ ]:
#### Let's try the following:

In [ ]:
# print the z first:
print ( z )

In [ ]:
# print z till 10 and z from 2 to 5
print( z [ : 10 ] )
print( z [ 1: 5  ] )

In [ ]:
# print all elements from 6 onwards:

print( z[ 5 :  ] )

In [ ]:
# print z from 12 to 2 with a -2 step; print z from 10 to end with step of 2
print( z [ 11 : 0: -2 ] )
#print( z [  ] )

### Let’s now assign a value of 40 to z[4] and of 42 to z[11:13]. Does it work?

In [ ]:
z[ 4 ] = 40 
z[ 11: 13] = 42
print( z )

### Print all values of z that are larger than 10 :

In [ ]:
# how would you do this?
z > 10

In [ ]:
# then:
print( z[ z> 10 ] )

### now print all  values that are smaller than 3 :

### what does z<3 alone give you?


In [ ]:
print( z < 3)

In [ ]:
print( z[ z< 3 ])


### now what if you want to have multiple conditions? 

In [ ]:
print( z [ ( z > 10 ) & ( z < 15 ) ] )   # ---> mask for data that both z > 10 and z < 15



In [ ]:
print( z )

### also, if you want to know *where* (which elements of) an array meet a specific criterion use the numpy where statement:


In [ ]:
print( np.where ( z < 14 ) )


In [ ]:
print( z[ np.where ( z < 14 ) ] )

In [ ]:
plt.figure( figsize = ( 4, 4 )  )
plt.plot( q[ q< 4 ]  , q_cos[ q < 4 ]  , color= 'red'  ) 
plt.plot( q[ q< 4 ]  , q_sin[ q < 4]  , color= 'blue' )
plt.ylim( 0, 1.01)

### Then let’s plot all parts of q_cos and q_sin that are larger than 0:

In [ ]:
#try to use np.where() to do this:
plt.figure( figsize = ( 4 , 4 ) )

plt.plot( q [ q_cos > 0 ], q_cos[ q_cos > 0 ],    
         color = 'red' )
plt.plot( q [ q_sin > 0] , q_sin[ q_sin >0 ], 
         color = 'blue', linestyle = 'none', marker = 'o' )
plt.xlim(0,10) 

In [ ]:
### of course you might have noticed that you don't even need the np.where at all here ;)  


In [ ]:
plt.figure( figsize = ( 12, 10 ) )

plt.plot( q    [   ],  
          q_cos[   ], color='red')
plt.plot( q    [   ],  
          q_sin[   ], color='blue')
plt.xlim(0,10) 

In [ ]:
## why does this work? 
# q_cos > 0 gives True False:
#print( q_cos > 0)
# so q [  q_cos > 0  ] will give you only the ones where it is True, i.e., you have already filtered it:
#test1 = q [  q_cos > 0  ]
#print ( test1 [ 10 : 20 ] )
#print ( q [ 10 : 20 ] )

### you can also mask in 2-dimensions:



In [ ]:
tst1 = np.array( [ [ 1, 1, 1 ], [ 2, -2, 2 ], [ -4, -4, 4 ] ] )
tst2 = np.array( [ [ 1, 1, 1 ], [ 2, -2, 2 ], [ -3, 3, 3 ] ] )

In [ ]:
print( tst1, '\n\n', tst2 )

In [ ]:
q_tst1 = tst1[ np.where( ( tst1 < 0 ) & ( tst2 < 0 ) )  ] 

In [ ]:
print( q_tst1 )

In [ ]:
np.where( ( tst1 < 0 ) & ( tst2 < 0 ) )

In [ ]:
np.where(  tst1 < 0 )

### can you see how we can add the x-axis < 6 and >1  in the q [ .....]  command?

In [ ]:
plt.figure( figsize = ( 12, 10 ) )

plt.plot(  q[  ], q_cos[  ]  )

### now use where() to only plot where q_cos >0, and 1 < q < 6

In [ ]:
plt.figure( figsize = ( 12, 10 ) )

plt.plot( q    [ np.where(  ) ],  
          q_cos[ np.where(  ) ], color='red')

plt.plot( q    [ np.where(  ) ],  
          q_sin[ np.where(  ) ], color='blue')

### i.e., you can use the >, <, where statements as a mask, to only show/ work with data that satisfy a specific criterion in any dimensions you want


### some more where cases:

In [ ]:
test_1 = np.arange(9).reshape((3, 3))

In [ ]:
print( test_1 )

In [ ]:
# make variable test_2 that is 4 times all elements of test_1, where test_1 is less than 4:



In [ ]:
print( test_2 )

In [ ]:
# you can also do this with np.where()


In [ ]:
#  can also use masks with x, y condition and return different array:
a = np.array( [[0, 1, 2],
               [0, 2, 4],
               [0, 3, 6] ] )

In [ ]:
print ( a , '\n')
print ( np.where( a < 4, a, -1 ) ) # -1 is broadcast   

In [ ]:
b = np.array( [[0, 1, 2],
               [3, 4, 5],
               [7, 8, 9] ] )

In [ ]:
print ( np.where(a > 4, -1 , b * 10 ) ) # -1 is broadcast 

In [ ]:
# same with: 
#a = np.arange(10)

In [ ]:
#print( a )
#print( np.where(a < 5, -3 , a) )


### Practice more slicing of 2D or ND arrays :

In [ ]:

my_2d_array = np.array( [ [ 1  , 2 , 3 , 4 , 5  ], 
                          [ 12 , 15, 16, 22, 18 ], 
                          [ 42 , 54, 53, 67, 88 ] , 
                          [ -41, 36, 98, 10, 12 ]  ] )


In [ ]:
print( my_2d_array)

In [ ]:
# how do I get " 53 " ?

In [ ]:
# how do I get the " 10 " ?

In [ ]:
# how do I get the slice:  16 22 53 67 ?


In [ ]:
a = np.array( [ 1, 2, 3, 4] )
print(np.where( a > 2 ))

In [ ]:
a = np.array([[0, 1, 2],
              [0, 6, 4],
              [0, 3, 6]])

In [ ]:
print( np.where( a > 2 ))

In [ ]:
a[ np.where( a > 2 ) ]